name: Package

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    # - uses: jurplel/install-qt-action@v2
    #   with:
    #     mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
    - name: Install dependencies
      run: sudo apt-get install -y qtbase5-dev libglu1-mesa-dev

    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target install

    - uses: actions/upload-artifact@v2
      with:
        name: Plater-Linux-${{github.sha}}
        path: ${{github.workspace}}/build/installed

  # Windows:
  #   runs-on: windows-latest

  #   steps:
  #   - uses: jurplel/install-qt-action@v2
  #     with:
  #        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
  #        arch: win64_msvc2019_64
  #        modules: all

  #   - uses: actions/checkout@v2

  #   - name: Create Build Environment
  #     run: cmake -E make_directory ${{github.workspace}}/build

  #   - name: Configure CMake
  #     shell: bash
  #     working-directory: ${{github.workspace}}/build
  #     run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE

  #   - name: Build
  #     working-directory: ${{github.workspace}}/build
  #     shell: bash
  #     run: cmake --build . --config $BUILD_TYPE

  #   - name: Package
  #     working-directory: ${{github.workspace}}/build
  #     shell: bash
  #     run: cmake --build . --config $BUILD_TYPE --target package
